I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/images/location/splunk.rpy", line 11, in script
    call screen splunkOverview
ScriptError: could not find label 'splunkmltk'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\temp\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\temp\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\temp\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\temp\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/images/location/splunk.rpy", line 11, in script
    call screen splunkOverview
  File "C:\temp\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'splunkmltk'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Blue Team Training With L.A.M.E. Creations 1.0
Sat Apr  6 14:10:31 2024
